framework:
    default_locale: '%locale%'
    translator:
        default_path: '%kernel.project_dir%/translations'
        enabled_locales: '%available_locales%'
        fallbacks:
            - '%locale%'
